version: '2'

services:

  postgres:
    restart: unless-stopped
    image: docker.io/bitnami/postgresql:15
    volumes: 
     - semaphore-postgres:/var/lib/postgresql/data
    environment:
      - POSTGRESQL_USERNAME=semaphore
      - POSTGRESQL_DATABASE=semaphore
      - POSTGRESQL_PASSWORD=semaphore
      - POSTGRESQL_POSTGRES_PASSWORD=changeme
  
  semaphore:
    restart: unless-stopped
    ports:
      - 3000:3000
    image: semaphore:ansible_9.2.0
    environment:
      SEMAPHORE_DB_USER: semaphore
      SEMAPHORE_DB_PASS: semaphore
      SEMAPHORE_DB_HOST: postgres
      SEMAPHORE_DB_PORT: 5432
      SEMAPHORE_DB_DIALECT: postgres
      SEMAPHORE_DB: semaphore
      SEMAPHORE_PLAYBOOK_PATH: /tmp/semaphore/
      SEMAPHORE_ADMIN_PASSWORD: changeme
      SEMAPHORE_ADMIN_NAME: admin
      SEMAPHORE_ADMIN_EMAIL: admin@localhost
      SEMAPHORE_ADMIN: admin
      SEMAPHORE_ACCESS_KEY_ENCRYPTION: gs72mPntFATGJs9qK0pQ0rKtfidlexiMjYCH9gWKhTU=
      SEMAPHORE_LDAP_ACTIVATED: 'no'
    depends_on:
      - postgres

volumes:
  semaphore-postgres:
