name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag semaphore:$(cat Dockerfile |grep FROM|cut -d ':' -f2)-$(cat requirements.txt |grep ansible==|sed 's/==/_/g')
